
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 22 15:47:33 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 7;
  public static final int ASSIGNMENT = 27;
  public static final int NUMCONST = 45;
  public static final int NOTEQUAL = 20;
  public static final int LPAREN = 33;
  public static final int GREATER = 21;
  public static final int SEMI = 30;
  public static final int CONTINUE = 14;
  public static final int INTERFACE = 5;
  public static final int MINUS = 40;
  public static final int LESS = 23;
  public static final int FOR = 18;
  public static final int RPAREN = 34;
  public static final int AND = 25;
  public static final int OR = 26;
  public static final int COMMA = 31;
  public static final int CLASS = 4;
  public static final int INC = 28;
  public static final int PLUS = 39;
  public static final int LESSEQ = 24;
  public static final int IF = 16;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 19;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MOD = 43;
  public static final int IDENT = 44;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int LBRACE = 37;
  public static final int ELSE = 17;
  public static final int LSQUARE = 35;
  public static final int ENUM = 6;
  public static final int READ = 10;
  public static final int CHARCONST = 46;
  public static final int RSQUARE = 36;
  public static final int RBRACE = 38;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int GREATEREQ = 22;
  public static final int DEC = 29;
  public static final int DIVISION = 42;
  public static final int IMPLEMENTS = 15;
  public static final int MULTIPLICATION = 41;
  public static final int PRINT = 9;
}

